Move sorting logic to artifact
heroku/buildpacks-go pull request #246
Opened 2024-04-03 01:28 UTC by runesoerensen

2024-04-03 14:13 UTC, colincasey commented on common/inventory-utils/src/inv.rs
> +    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
Add some unit tests here.

2024-04-03 14:13 UTC, colincasey commented on common/inventory-utils/src/inv.rs
> +    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
Add some unit tests here.

2024-04-03 14:13 UTC, colincasey commented on common/go-utils/src/bin/diff_inventory.rs
> +        list.reverse();
Does this mean the default sorting is version ascending (i.e.; oldest to newest)? Shouldn't it be the opposite so you don't need to `reverse()` it?

2024-04-04 16:41 UTC, joshwlewis requested changes
Implementation looks good, but I agree that it needs unit tests.

2024-05-16 00:16 UTC, closed without merging